accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    
    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    
    path('post/', views.CreatePhotoView.as_view(), name='post'),
    
    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),
    
    path('photos/<int:category>',
         views.CategoryView.as_view(),
         name = 'photos_cat'
         ),

    path('user-list/<int:user>',
         views.UserView.as_view(),
         name = 'user_list'
         ),
    
    path('photo-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'photo_detail'
         ),
    
    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

    path('photo/<int:pk>/delete/',
         views.PhotoDeleteView.as_view(),
         name = 'photo_delete'
         ),
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('photo.urls')),
    
    path('', include('accounts.urls')),
    
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),
]

urlpatterns += static(
  settings.MEDIA_URL,
  document_root=settings.MEDIA_ROOT
  )

photo/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(
        verbose_name='カテゴリ', 
        max_length=20)
    
    def __str__(self):
        return self.title

class PhotoPost(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
        )
    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
        )
    title = models.CharField(
        verbose_name='タイトル', 
        max_length=200        
        )
    comment = models.TextField(
        verbose_name='コメント',  
        )
    image1 = models.ImageField(
        verbose_name='イメージ1',
        upload_to = 'photos'   
        )
    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to = 'photos',  
        blank=True,            
        null=True              
        )
    posted_at = models.DateTimeField(
        verbose_name='投稿日時', 
        auto_now_add=True       
        )
    
    def __str__(self):
        return self.title

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    class Meta:
        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']
        

photo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import PhotoPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import PhotoPost
from django.views.generic import DetailView
from django.views.generic import DeleteView

class IndexView(ListView):
    '''トップページのビュー
    '''
    template_name ='index.html'
    queryset = PhotoPost.objects.order_by('-posted_at')
    paginate_by = 9

@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    '''写真投稿ページのビュー
    
    PhotoPostFormで定義されているモデルとフィールドと連携して
    投稿データをデータベースに登録する
    
    Attributes:
      form_class: モデルとフィールドが登録されたフォームクラス
      template_name: レンダリングするテンプレート
      success_url: データベスへの登録完了後のリダイレクト先
    '''
    form_class = PhotoPostForm
    template_name = "post_photo.html"
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う
        
        parameters:
          form(django.forms.Form):
            form_classに格納されているPhotoPostFormオブジェクト
        Return:
          HttpResponseRedirectオブジェクト:
            スーパークラスのform_valid()の戻り値を返すことで、
            success_urlで設定されているURLにリダイレクトさせる
        '''
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    '''投稿完了ページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
    '''
    template_name ='post_success.html'

class CategoryView(ListView):
    '''カテゴリページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    template_name ='index.html'
    paginate_by = 9

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''     
      category_id = self.kwargs['category']
      categories = PhotoPost.objects.filter(
        category=category_id).order_by('-posted_at')
      return categories

class UserView(ListView):
    '''ユーザーの投稿一覧ページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    template_name ='index.html'
    paginate_by = 9

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''
      user_id = self.kwargs['user']
      user_list = PhotoPost.objects.filter(
        user=user_id).order_by('-posted_at')
      return user_list

class DetailView(DetailView):
    '''詳細ページのビュー
    
    投稿記事の詳細を表示するのでDetailViewを継承する
     Attributes:
      template_name: レンダリングするテンプレート
      model: モデルのクラス
    '''
    template_name ='detail.html'
    model = PhotoPost

class MypageView(ListView):
    '''マイページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    template_name ='mypage.html'
    paginate_by = 9

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''
      queryset = PhotoPost.objects.filter(
        user=self.request.user).order_by('-posted_at')
      return queryset
  
class PhotoDeleteView(DeleteView):
    '''レコードの削除を行うビュー
    
    Attributes:
      model: モデル
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
      success_url: 削除完了後のリダイレクト先のURL
    '''
    model = PhotoPost
    template_name ='photo_delete.html'
    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
      '''レコードの削除を行う
      
      Parameters:
        self: PhotoDeleteViewオブジェクト
        request: WSGIRequest(HttpRequest)オブジェクト
        args: 引数として渡される辞書(dict)
        kwargs: キーワード付きの辞書(dict)
                {'pk': 21}のようにレコードのidが渡される
      
      Returns:
        HttpResponseRedirect(success_url)を返して
        success_urlにリダイレクト
      '''
      return super().delete(request, *args, **kwargs)

photo/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>{% block title %}{% endblock %}</title>
    
    <!-- staticでfavicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon"
　　        href={% static 'assets/favicon.ico' %} />
　　       
    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>    
  </head>
  
  <body>
    <!-- ページのヘッダー-->
    <header>
      <!-- ナビゲーションバーのヘッダー-->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文-->
              <h4 class="text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できる写真投稿サイトです。
                自分で撮影した写真なら何でもオッケー！
                でも、カテゴリに属する写真に限ります。
                コメントも付けてください！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー-->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="{% url 'photo:mypage' %}"
                       class="text-white">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}"
                       class="text-white">ログアウト</a></li>
                <li><a href="{% url 'password_reset' %}"
                       class="text-white">パスワードのリセット</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}"
                       class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}"
                       class="text-white">ログイン</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- ナビゲーションバー-->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク-->
          <a href="{% url 'photo:index' %}"
             class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="20" height="20" fill="none"
                 stroke="currentColor"
                 stroke-linecap="round"
                 stroke-linejoin="round"
                 stroke-width="2"
                 aria-hidden="true"
                 class="me-2"
                 viewBox="0 0 24 24">
                 <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                 <circle cx="12" cy="13" r="4"/></svg>
            <!-- リンクテキスト-->
            <strong>Photo Gallery</strong>
          </a>
          <!-- トグルボタン-->
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarHeader"
                  aria-controls="navbarHeader"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    
    <!-- メインコンテンツ-->
    <main>
      <!-- <main>タグの要素をすべて削除して以下に書き換え-->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->
      {% block contents %}{% endblock %}
    </main>
    
    <!-- フッター -->
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p class="mb-1">
          Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
      </div>
    </footer>
    
    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>      
  </body>
</html>

photo/templates/detail.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
          <div class="col offset-3">
            <h2>{{object.title}}</h2>
            <p>{{object.comment}}</p>
            <br>
            <p>{{object.posted_at}}に投稿</p>
            <p><img src="{{ object.image1.url }}"></img></p>
            {% if object.image2 %}
              <p><img src="{{ object.image2.url }}"></img></p>
            {% endif %}
            
            {% if request.user == object.user %}
            <form method="POST">
            <a href="{% url 'photo:photo_delete' object.pk %}"
               class="btn btn-primary my-2">削除する</a>
            {% endif %}
            
          </dv>
        </dv>
      </dv>
      {% endblock %}

photo/templates/index.html
{% extends 'base.html' %}

{% block title %}Photo Gallery{% endblock %}

    {% block contents %}

    {% include "photos_title.html" %}

    {% include "photos_list.html" %}

    {% include "pagination.html" %}

    {% endblock %}

photo/templates/mypage.html
{% extends 'base.html' %}
{% block title %}Mypage{% endblock %}

      {% block contents %}
      
      
      {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
          <h4>{{user.username}}さんのマイページ</h4>
          {% if object_list.count == 0 %}
            <p>{{user.username}}さんの投稿はありません</p>
          {% else %}
            <p>投稿<strong>{{object_list.count}}</strong>件</p>
          {% endif %}
          <a href="{% url 'photo:post' %}">投稿する</a>
        </div>
        <hr>
      {% endif %}
      
      {% include "photos_list.html" %}
        
      {% include "pagination.html" %}

      {% endblock %}

photo/templates/pagination.html
<ul class="pagination"
    style="justify-content:center">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link"
             href="?page={{ page_obj.previous_page_number }}"
             aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}"
           aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

photo/templates/photo_delete.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
          <div class="col offset-3">
            <form method="POST">
              <br>
              <p>削除してもいいですか?</p>
              {% csrf_token %}
              <button class="btn btn-primary my-2"
                      type="submit">削除</button>
              <a href="{% url 'photo:photo_detail' object.pk %}"
                 class="btn btn-secondary my-2">キャンセル</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

photo/templates/photos_list.html
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for record in object_list %}
      <div class="col">
        <div class="card shadow-sm">
          <img src="{{ record.image1.url }}"
               class="bd-placeholder-img card-img-top"
               width="100%" height="225"
               xmlns="http://www.w3.org/2000/svg"
               role="img" aria-label="Placeholder: Thumbnail"
               preserveAspectRatio="xMidYMid slice"
               focusable="false">
               <title>Placeholder</title>
               <rect width="100%" height="100%" fill="#55595c"/>
          </img>
          <div class="card-body">
            <p class="card-text">
              {{record.title}}
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button"
                        class="btn btn-sm btn-outline-secondary"
onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">
                        View</button>
                <button type="button"
                        class="btn btn-sm btn-outline-secondary"
onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'">
                        {{record.category.title}}</button>
              </div>
              <a href="{% url 'photo:user_list' user=record.user.id %}">
                <small class="text-muted">
                  {{record.user.username}}</small>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

photo/templates/photos_title.html
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Photo Gallery</h1>
        <p class="lead text-muted">
          コメントを見て写真に描かれた世界に思いを馳せましょう。
          素敵な写真とコメントをお待ちしています!</p>
        <p>
          {% if user.is_authenticated %}
          <a href="{% url 'photo:post' %}"
             class="btn btn-primary my-2">投稿する</a>
          <a href="{% url 'accounts:logout' %}"
             class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
          <a href="{% url 'accounts:signup' %}"
             class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}"
             class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

photo/templates/post_photo.html
{% extends 'base.html' %}
{% block title %}Post{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
          <div class="col offset-2">
            <form method="POST"
                  enctype="multipart/form-data">
              {% csrf_token %}
              <table>
                <tr>
                  <th>カテゴリ</th>
                  <td>{{ form.category }}</td>
                </tr>
                <tr>
                  <th>タイトル</th>
                  <td>{{ form.title }}</td>
                </tr>
                <tr>
                  <th>コメント</th>
                  <td>{{ form.comment }}</td>
                </tr>
                <tr>
                  <th>画像1</th>
                  <td>{{ form.image1 }}</td>
                </tr>
                <tr>
                  <th>画像2</th>
                  <td>{{ form.image2 }}</td>
                </tr>
              </table>
              <hr>
              <button type="submit">投稿する</button>
            </form>        
          </dv>
        </dv>
      </dv>
      {% endblock %}

photo/templates/post_success.html
{% extends 'base.html' %}

{% block title %}Post Success{% endblock %}

      {% block contents %}
      <br><br>
      <div class="container">
        <div class="row">
          <div class="col offset-2">
            <h4>投稿が完了しました!</h4>  
          </dv>
        </dv>
      </dv>
      {% endblock %}